kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "kibana-config-controller.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get", "list", "watch"]