kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "kibana.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kibana.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kibana.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}

