apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kibana.serviceAccountName" . }}
  namespace: {{ default .Release.Namespace .Values.global.namespace | quote }}
  labels:
    app: {{ template "kibana.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
